### ISSUE TITLE
GPT testing framework

### ISSUE THREAD

**Issue by craterink** [piercefreeman/gpt-json#10]
Let's say you want to somehow rigorously test (or constrain) the behavior of an AI system you've built. In deterministic systems we use testing frameworks / TDD. But with the dynamism of AI outputs it's not so obvious.

It would be fun to build a GPT testing framework into this repo. Such a framework might support a few varieties of testing:

1) **Discrete output testing**. User wants to test a GPTJSON interaction where GPT is making a discrete/deterministic decision as part of its JSON output. E.g., classifying sentiment into `[negative, neutral, positive]`. This seems pretty straightforward to build and isn't doing anything new except maybe needs some clever design and prompt caching/diffing.

2) **Statistical signature testing**. User wants to test that GPT interaction outputs satisfy some statistic, such as min/max # sentences. Does or does not contain certain keywords. Etc. This is straightforward as well, but by considering the usecases/statistics a framework could make it really easy to write such tests.

2) **Semantic distance testing**. This is a more experimental idea. Suppose the user wants to make sure GPT outputs ARE "close enough" to a `gold_output`, or ARE NOT "close enough" to a `bad_output`. E.g., a math tutor shouldn't give away answers. Technically, this could be implemented as a text classifier applied to outputs, possibly using GPT under the hood 🐍.

**Comment by piercefreeman** [comment]
@craterink I like this a lot and have felt a similar need during programatic / CI testing of models. How do you see this overlapping with something like the openai https://github.com/openai/evals?

My thoughts at this time is that a testing framework doesn't fit squarely into the focused intent of `gpt-json` as a library to help with model querying. I wouldn't want users that are looking for a prompting module to be forced to bring in a whole lot of testing dependencies (that with them would probably have to bring in things like scikit, numpy, etc).

However these needs are commonly enough bundled that it could make sense to include this kind of testing framework in this project as a sub-dependency. I'm thinking for now we can start with a new `gpt-testing-harness` or similar folder in the main repository root that can define its own pyproject.toml file, and once mature enough hook it up to CI and deploy as an independent python package.

Does that sound reasonable?

**Comment by craterink** [comment]
That sounds groovy, and reasonable. Let's do it!
