### ISSUE TITLE
I'd like to see the raw response.

### ISSUE THREAD

**Issue by jaded0** [piercefreeman/gpt-json#15]
Message: 'JSON decode error, likely malformed json input'
Arguments: (JSONDecodeError("Expecting ',' delimiter: line 4 column 30 (char 159)"),)

I just get the error ^ when, presumably, GPT has returned a bad response. I have no way of knowing what is going wrong if I can't actually see what the returned string is. 

Related to this, I want to be able to see the full prompt that was sent to openai, as well.

**Comment by piercefreeman** [comment]
@jaded0 You can enable verbose debugging to see the raw request and response values in your console:

```python
logger = logging.getLogger("gptjson_logger") # the old version had a different logger name but the logic is still the same
logger.setLevel(logging.DEBUG)
```

Are you interested in a programatic return value to access these values as well? If so I'd love to hear more about what use case you have in mind so I can think about the best approach.
