### ISSUE TITLE
Claude integration 

### ISSUE THREAD

**Issue by dgonier** [piercefreeman/gpt-json#29]
This is great. I also use Claude because of the context windows. The format is very similar can we add an option for Claude (anthropic)

**Comment by piercefreeman** [comment]
@dgonier Claude is planned and currently being worked on in https://github.com/piercefreeman/gpt-json/pull/25. Feel free to give that branch a try and see if it fits your needs! Feedback welcome.

**Comment by dgonier** [comment]
Thank you!

"A society grows when the old plant trees whose shade they know they will
never sit under." -Greek Proverb

**Comment by ishaan-jaff** [comment]
Addressed this here: https://github.com/piercefreeman/gpt-json/pull/35
