### ISSUE TITLE
I created a Javascript/ Typescript Version

### ISSUE THREAD

**Issue by vincenzodomina** [piercefreeman/gpt-json#31]
For my Javascript fellows coming across this awesome tool:

I created a Javascript version, for now only the transformation part, as i needed only that.

The only change i made for now, is that I use it as middleware to modify the GPT response string only.

TLDR: GPT Response string in -> JSON string out

Any help appreciated!

[https://github.com/vincenzodomina/gpt-json-js](https://github.com/vincenzodomina/gpt-json-js)

**Comment by piercefreeman** [comment]
Thanks for the interest @vincenzodomina! Will take a look next time I'm in Node land.
