### ISSUE TITLE
Support pydantic v2

### ISSUE THREAD

**Issue by stevesimmons** [piercefreeman/gpt-json#34]
Hi Pierce. 

Do you have any plans to support Pydantic v2?

From running the unit tests with pyproject.toml edited for Pydantic v2, the main point where errors occur is at `value.type_` here::

```
gpt_json/prompts.py
32:            elif issubclass(value.type_, BaseModel):
33:                payload.append(f'"{key}": {generate_payload(value.type_)}')
35:                payload.append(f'"{key}": {value.type_.__name__.lower()}')
```

**Comment by piercefreeman** [comment]
Hey @stevesimmons, yes Pydantic 2 is certainly on my list. Let me investigate over the weekend to see if the fix is an easy one and I'll get back to you.

**Comment by piercefreeman** [comment]
Put up an initial PR to support both V1 and V2. It's passing the current test cases, but give it a try in your deployment and give a shout if anything seems amiss:
https://github.com/piercefreeman/gpt-json/pull/37
