### ISSUE TITLE
Custom BaseURL

### ISSUE THREAD

**Issue by LuggaPugga** [piercefreeman/gpt-json#46]
can i somehow change the baseurl to use openrouter for example?

**Comment by piercefreeman** [comment]
@LuggaPugga We support the same environment variables as the `openai` library does, so you should be able to export `OPENAI_BASE_URL` to modify the base url.

https://github.com/openai/openai-python/blob/0de7419c962805bbe9db18d99524b66673f7f8e9/src/openai/_client.py#L330C40-L330C55

**Comment by LuggaPugga** [comment]
that helps a lot thanks.
